export const MODULE_NAME = 'THEME_CHANGE_MODULE_NAME';

export enum THEME_CHANGE_OPTION {
  LIGHT = 0,
  DARK = 1,
  SYSTEM = 2,
}

export type THEME_CHANGE_OPTION_TYPE =
  | THEME_CHANGE_OPTION.LIGHT
  | THEME_CHANGE_OPTION.DARK
  | THEME_CHANGE_OPTION.SYSTEM;
